## Fastly price rating configurations
## The price format is the following:
##
## [region]
## bandwidth = [number: bandwith price rate per unit (GB)]
## requests = [number: requests price rate per unit (10K)]
## computeRequests = [number: compute request price rate per unit (1M)]
## computeDurations = [number: compute duration price rate per unit (GB-Sec)]
##
## Also, probably you have a contract of volume discount with Fastly,
## Then you can express gradual price rate as an array.
## Following the example of bandwidth gradual discount:
##
## [usa]
## bandwidth = [
##   { threshold = 5000, price = 0.1 },
##   { threshold = 10000, price = 0.08 },
##   { threshold = -1, price = 0.05 },
## ]
##
## On the above case, request in usa region will be calculate as:
## 1. Until 5,000 units (5,000 GB = 5TB), price rate is 0.1 doller
## 2. Until 10,000 units (10,000 GB = 10TB), price rate is 0.08 doller
## 3. Over the 10,000 units, price rate is 0.05 (-1 means unlimited, over the unit)
##
## You MUST specify all reagins price rate that Fastly bills for:
##   asia, europe, anzac, asia_india, asia_southkorea, africa_std, southamerica_std, usa
##
## Following price rates are based on Fastly Official Documentation:
## https://www.fastly.com/pricing
[asia]
bandwidth = [
  {threshold = 10000, price = 0.19},
  {threshold = -1, price = 0.14},
]
requests = 0.0090
computeRequests = 0.50
computeDurations = 0.000035

[europe]
bandwidth = [
  {threshold = 10000, price = 0.12},
  {threshold = -1, price = 0.08},
]
requests = 0.0075
computeRequests = 0.50
computeDurations = 0.000035

[anzac]
bandwidth = [
  {threshold = 10000, price = 0.19},
  {threshold = -1, price = 0.14},
]
requests = 0.0090
computeRequests = 0.50
computeDurations = 0.000035

[asia_india]
bandwidth = [
  {threshold = 10000, price = 0.28},
  {threshold = -1, price = 0.24},
]
requests = 0.0160
computeRequests = 0.50
computeDurations = 0.000035

[asia_southkorea]
bandwidth = [
  {threshold = 10000, price = 0.28},
  {threshold = -1, price = 0.24},
]
requests = 0.0160
computeRequests = 0.50
computeDurations = 0.000035

[africa_std]
bandwidth = [
  {threshold = 10000, price = 0.28},
  {threshold = -1, price = 0.24},
]
requests = 0.0160
computeRequests = 0.50
computeDurations = 0.000035

[southamerica_std]
bandwidth = [
  {threshold = 10000, price = 0.19},
  {threshold = -1, price = 0.14},
]
requests = 0.0090
computeRequests = 0.50
computeDurations = 0.000035

[usa]
bandwidth = [
  {threshold = 10000, price = 0.12},
  {threshold = -1, price = 0.08},
]
requests = 0.0075
computeRequests = 0.50
computeDurations = 0.000035

